import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const catalogPath = join(root, 'catalog.json')
const generatedPath = join(root, 'src/data/hub.generated.ts')
const installDir = join(root, 'public/install')
const siteOrigin = 'https://hapwi.github.io'

const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN || ''

function githubHeaders(extra = {}) {
  return {
    Accept: 'application/vnd.github+json',
    'User-Agent': 'hapwi-github-io-catalog-sync',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
    ...extra,
  }
}

async function githubJson(url) {
  const response = await fetch(url, { headers: githubHeaders() })
  if (!response.ok) {
    throw new Error(`${url} failed (${response.status})`)
  }
  return response.json()
}

function toSlug(repo, explicit) {
  if (explicit) return explicit
  return repo.split('/')[1]
}

async function copyInstallScript(owner, repo, branch, sourcePath, slug) {
  const rawUrl = `https://raw.githubusercontent.com/${owner}/${repo}/${encodeURIComponent(branch)}/${sourcePath}`
  const response = await fetch(rawUrl, {
    headers: githubHeaders({ Accept: 'text/plain' }),
  })
  if (!response.ok) {
    throw new Error(`could not fetch ${rawUrl} (${response.status})`)
  }
  const body = await response.text()
  if (!body.startsWith('#!')) {
    throw new Error(`${rawUrl} does not look like a shell script`)
  }
  await writeFile(join(installDir, `${slug}.sh`), body, { mode: 0o644 })
  return `${siteOrigin}/install/${slug}.sh`
}

function serializeGenerated(syncedAt, projects) {
  return `// Generated by scripts/sync-catalog.mjs. Do not edit.
export const hubSyncedAt = ${JSON.stringify(syncedAt)}

export const hubProjects = ${JSON.stringify(projects, null, 2)} as const
`
}

async function main() {
  const catalog = JSON.parse(await readFile(catalogPath, 'utf8'))
  const entries = Array.isArray(catalog.projects) ? catalog.projects : []

  await mkdir(installDir, { recursive: true })
  const existing = await readdir(installDir).catch(() => [])
  await Promise.all(
    existing
      .filter((name) => name.endsWith('.sh'))
      .map((name) => rm(join(installDir, name))),
  )

  const projects = []
  for (const entry of entries) {
    if (!entry?.repo || !String(entry.repo).includes('/')) {
      throw new Error(`catalog entry is missing repo: ${JSON.stringify(entry)}`)
    }
    const [owner, repo] = entry.repo.split('/')
    const data = await githubJson(
      `https://api.github.com/repos/${owner}/${repo}`,
    )
    const slug = toSlug(entry.repo, entry.slug)
    let installUrl = null
    if (entry.install) {
      installUrl = await copyInstallScript(
        owner,
        repo,
        data.default_branch,
        entry.install,
        slug,
      )
    }

    projects.push({
      slug,
      name: entry.name ?? data.name,
      tagline: entry.tagline ?? '',
      description: entry.description ?? data.description ?? '',
      repoUrl: data.html_url,
      homepage: data.homepage || null,
      language: data.language ?? null,
      stars: data.stargazers_count ?? 0,
      pushedAt: data.pushed_at,
      topics: data.topics ?? [],
      installUrl,
      installCommand: installUrl ? `curl -fsSL ${installUrl} | bash` : null,
    })
  }

  const syncedAt = new Date().toISOString()
  await mkdir(dirname(generatedPath), { recursive: true })
  await writeFile(generatedPath, serializeGenerated(syncedAt, projects))
  console.log(`synced ${projects.length} project(s) from catalog.json`)
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
