/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TampermonkeyRouteImport } from './routes/tampermonkey'
import { Route as DiscordThemesRouteImport } from './routes/discord-themes'
import { Route as IndexRouteImport } from './routes/index'

const TampermonkeyRoute = TampermonkeyRouteImport.update({
  id: '/tampermonkey',
  path: '/tampermonkey',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordThemesRoute = DiscordThemesRouteImport.update({
  id: '/discord-themes',
  path: '/discord-themes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discord-themes': typeof DiscordThemesRoute
  '/tampermonkey': typeof TampermonkeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discord-themes': typeof DiscordThemesRoute
  '/tampermonkey': typeof TampermonkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discord-themes': typeof DiscordThemesRoute
  '/tampermonkey': typeof TampermonkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/discord-themes' | '/tampermonkey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discord-themes' | '/tampermonkey'
  id: '__root__' | '/' | '/discord-themes' | '/tampermonkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscordThemesRoute: typeof DiscordThemesRoute
  TampermonkeyRoute: typeof TampermonkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tampermonkey': {
      id: '/tampermonkey'
      path: '/tampermonkey'
      fullPath: '/tampermonkey'
      preLoaderRoute: typeof TampermonkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord-themes': {
      id: '/discord-themes'
      path: '/discord-themes'
      fullPath: '/discord-themes'
      preLoaderRoute: typeof DiscordThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscordThemesRoute: DiscordThemesRoute,
  TampermonkeyRoute: TampermonkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
