// Generated by scripts/sync-catalog.mjs. Do not edit.
export const hubSyncedAt = "2026-08-24T12:49:44.146Z"

export const hubProjects = [
  {
    "slug": "period-space",
    "name": "period-space",
    "tagline": "Double-space becomes a period, everywhere on Linux.",
    "description": "macOS-style double-space period on Linux. Works everywhere: terminals, TTY, Wayland, X11, editors, browsers.",
    "repoUrl": "https://github.com/hapwi/period-space",
    "homepage": null,
    "language": "Python",
    "stars": 2,
    "pushedAt": "2026-08-24T12:13:19Z",
    "topics": [
      "keyboard",
      "keyd",
      "linux",
      "tty",
      "wayland"
    ],
    "installUrl": "https://hapwi.github.io/install/period-space.sh",
    "installCommand": "curl -fsSL https://hapwi.github.io/install/period-space.sh | bash"
  },
  {
    "slug": "mmf-golden-gate-fixer",
    "name": "mmf-golden-gate-fixer",
    "tagline": "Restores Mac Mouse Fix button-drag Spaces on macOS 27 Golden Gate.",
    "description": "Unofficial companion that restores Mac Mouse Fix button-drag Spaces on macOS 27 Golden Gate.",
    "repoUrl": "https://github.com/hapwi/mmf-golden-gate-fixer",
    "homepage": null,
    "language": "Objective-C",
    "stars": 0,
    "pushedAt": "2026-08-22T12:16:32Z",
    "topics": [],
    "installUrl": null,
    "installCommand": null
  },
  {
    "slug": "codex-cleaner",
    "name": "codex-cleaner",
    "tagline": "Guided cleanup for local Codex Desktop and CLI state.",
    "description": "Safe, guided cleanup for local Codex Desktop and CLI state: audit clutter, archive chats, rotate logs, review restore backups, and manage archive storage without deleting history by default.",
    "repoUrl": "https://github.com/hapwi/codex-cleaner",
    "homepage": null,
    "language": "Python",
    "stars": 1,
    "pushedAt": "2026-06-16T07:20:26Z",
    "topics": [],
    "installUrl": null,
    "installCommand": null
  },
  {
    "slug": "bettergit",
    "name": "bettergit",
    "tagline": "Public TypeScript git tooling.",
    "description": "",
    "repoUrl": "https://github.com/hapwi/bettergit",
    "homepage": null,
    "language": "TypeScript",
    "stars": 0,
    "pushedAt": "2026-04-20T17:02:50Z",
    "topics": [],
    "installUrl": null,
    "installCommand": null
  }
] as const
