// Generated by scripts/sync-catalog.mjs. Do not edit.
export const hubSyncedAt = "2026-08-25T11:08:58.634Z"

export const hubProjects = [
  {
    "slug": "period-space",
    "name": "period-space",
    "tagline": "Double-space becomes a period, everywhere on Linux.",
    "description": "macOS-style double-space period on Linux. Works everywhere: terminals, TTY, Wayland, X11, editors, browsers.",
    "repoUrl": "https://github.com/hapwi/period-space",
    "homepage": null,
    "language": "Python",
    "stars": 3,
    "pushedAt": "2026-08-25T00:48:00Z",
    "topics": [
      "keyboard",
      "keyd",
      "linux",
      "tty",
      "wayland"
    ],
    "installUrl": "https://hapwi.github.io/install/period-space.sh",
    "installCommand": "curl -fsSL https://hapwi.github.io/install/period-space.sh | bash"
  },
  {
    "slug": "pastebridge",
    "name": "pastebridge",
    "tagline": "Copy on macOS, paste on Linux. Encrypted local clipboard sync.",
    "description": "Copy on macOS, paste on Linux. Encrypted local clipboard sync.",
    "repoUrl": "https://github.com/hapwi/pastebridge",
    "homepage": "https://hapwi.github.io/i",
    "language": "Rust",
    "stars": 2,
    "pushedAt": "2026-08-25T09:14:41Z",
    "topics": [
      "clipboard",
      "linux",
      "macos",
      "p2p",
      "rust"
    ],
    "installUrl": "https://hapwi.github.io/install/pastebridge.sh",
    "installCommand": "curl -fsSL https://hapwi.github.io/install/pastebridge.sh | bash"
  },
  {
    "slug": "mmf-golden-gate-fixer",
    "name": "mmf-golden-gate-fixer",
    "tagline": "Restores Mac Mouse Fix button-drag Spaces on macOS 27 Golden Gate.",
    "description": "Unofficial companion that restores Mac Mouse Fix button-drag Spaces on macOS 27 Golden Gate.",
    "repoUrl": "https://github.com/hapwi/mmf-golden-gate-fixer",
    "homepage": null,
    "language": "Objective-C",
    "stars": 1,
    "pushedAt": "2026-08-22T12:16:32Z",
    "topics": [],
    "installUrl": "https://hapwi.github.io/install/mmf-golden-gate-fixer.sh",
    "installCommand": "curl -fsSL https://hapwi.github.io/install/mmf-golden-gate-fixer.sh | bash"
  }
] as const
